// Generated from the Rust commands by `MELD_WRITE_BINDINGS=1 cargo test bindings_are_up_to_date`
// (src-tauri/src/ipc/bindings.rs, S5-011). Do not edit by hand.
/* eslint-disable */
// @ts-nocheck: generated helpers include unused declarations; the exported types are still checked where used.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async appUpdateCheck() : Promise<UpdateSummary | null> {
    return await TAURI_INVOKE("app_update_check");
},
/**
 * Downloads the signed update, verifies it (the plugin rejects a bad signature), backs up the database and
 * starts the installer, which closes and restarts Meld Desktop. Only called after the user clicks Install.
 */
async appUpdateInstall() : Promise<null> {
    return await TAURI_INVOKE("app_update_install");
},
async appOpenReleasesPage() : Promise<null> {
    return await TAURI_INVOKE("app_open_releases_page");
},
/**
 * Stops a command started with this `requestId` (S5-009). Unknown ids are remembered briefly,
 * in case the cancel overtakes the call it belongs to.
 */
async requestCancel(requestId: Token) : Promise<boolean> {
    return await TAURI_INVOKE("request_cancel", { requestId });
},
async ytmHistory() : Promise<RemoteHistoryPage> {
    return await TAURI_INVOKE("ytm_history");
},
async ytmRemoveFromHistory(token: Token) : Promise<null> {
    return await TAURI_INVOKE("ytm_remove_from_history", { token });
},
async spotifyProfile() : Promise<SpotifyProfile> {
    return await TAURI_INVOKE("spotify_profile");
},
async spotifyLibraryNode(folderUri: string | null) : Promise<SpotifyLibraryNode> {
    return await TAURI_INVOKE("spotify_library_node", { folderUri });
},
async spotifyPlaylists() : Promise<SpotifyPlaylistItem[]> {
    return await TAURI_INVOKE("spotify_playlists");
},
async spotifyPlaylistTracks(playlistId: SpotifyId, offset: number | null) : Promise<SpotifyTrackPage> {
    return await TAURI_INVOKE("spotify_playlist_tracks", { playlistId, offset });
},
async spotifyRemoveFromPlaylist(playlistId: SpotifyId, uid: SpotifyId) : Promise<null> {
    return await TAURI_INVOKE("spotify_remove_from_playlist", { playlistId, uid });
},
async spotifyMoveInPlaylist(playlistId: SpotifyId, uids: SpotifyId[], beforeUid: string | null) : Promise<null> {
    return await TAURI_INVOKE("spotify_move_in_playlist", { playlistId, uids, beforeUid });
},
async spotifyRenamePlaylist(playlistId: SpotifyId, newName: Name) : Promise<null> {
    return await TAURI_INVOKE("spotify_rename_playlist", { playlistId, newName });
},
async spotifyLikedTracks() : Promise<SpotifyLikedTracks> {
    return await TAURI_INVOKE("spotify_liked_tracks");
},
async spotifyMatchForYoutube(youtubeId: VideoId) : Promise<SpotifyTrackMatch | null> {
    return await TAURI_INVOKE("spotify_match_for_youtube", { youtubeId });
},
async spotifyOverrideYoutube(spotifyId: LibraryId, youtubeId: VideoId, title: Text, artist: Text) : Promise<null> {
    return await TAURI_INVOKE("spotify_override_youtube", { spotifyId, youtubeId, title, artist });
},
async spotifyResolveYoutube(youtubeId: string | null, title: Text, artist: Text, durationSec: number) : Promise<SpotifyTrackMatch | null> {
    return await TAURI_INVOKE("spotify_resolve_youtube", { youtubeId, title, artist, durationSec });
},
async spotifyAddToPlaylist(playlistId: SpotifyId, trackUri: SpotifyUri) : Promise<null> {
    return await TAURI_INVOKE("spotify_add_to_playlist", { playlistId, trackUri });
},
async ytmDeleteUploadedSong(entityId: Token) : Promise<boolean> {
    return await TAURI_INVOKE("ytm_delete_uploaded_song", { entityId });
},
async ytmRefetch(videoId: VideoId) : Promise<YtItem | null> {
    return await TAURI_INVOKE("ytm_refetch", { videoId });
},
async ytmToggleEpisodeSaved(videoId: VideoId, saved: boolean, setVideoId: string | null, item: YtItem | null) : Promise<null> {
    return await TAURI_INVOKE("ytm_toggle_episode_saved", { videoId, saved, setVideoId, item });
},
async localFilesPick() : Promise<LocalItem[]> {
    return await TAURI_INVOKE("local_files_pick");
},
async libraryLocalFiles() : Promise<LocalItem[]> {
    return await TAURI_INVOKE("library_local_files");
},
async libraryDownloads() : Promise<LocalItem[]> {
    return await TAURI_INVOKE("library_downloads");
},
async libraryPlayerCache() : Promise<YtItem[]> {
    return await TAURI_INVOKE("library_player_cache");
},
async ytmTogglePodcastSaved(podcastId: YtId, saved: boolean, title: Text, author: string | null, thumbnail: string | null) : Promise<null> {
    return await TAURI_INVOKE("ytm_toggle_podcast_saved", { podcastId, saved, title, author, thumbnail });
},
async downloadStart(item: YtItem, audioQuality: string | null) : Promise<null> {
    return await TAURI_INVOKE("download_start", { item, audioQuality });
},
async downloadInfo(songId: LibraryId) : Promise<DownloadInfo | null> {
    return await TAURI_INVOKE("download_info", { songId });
},
async downloadCancel(songId: LibraryId) : Promise<null> {
    return await TAURI_INVOKE("download_cancel", { songId });
},
async downloadRemove(songId: LibraryId) : Promise<null> {
    return await TAURI_INVOKE("download_remove", { songId });
},
async playerCacheRemove(songId: LibraryId) : Promise<null> {
    return await TAURI_INVOKE("player_cache_remove", { songId });
},
async playerCacheUsage() : Promise<PlayerCacheUsage> {
    return await TAURI_INVOKE("player_cache_usage");
},
/**
 * Empties the playback cache. Offline downloads are not touched.
 */
async playerCacheClear() : Promise<number> {
    return await TAURI_INVOKE("player_cache_clear");
},
async ytmPodcastChannels() : Promise<YtItem[]> {
    return await TAURI_INVOKE("ytm_podcast_channels");
},
async librarySavedPodcasts() : Promise<YtItem[]> {
    return await TAURI_INVOKE("library_saved_podcasts");
},
async ytmRefreshSavedPodcasts() : Promise<number> {
    return await TAURI_INVOKE("ytm_refresh_saved_podcasts");
},
async libraryDownloadedPodcasts() : Promise<LocalItem[]> {
    return await TAURI_INVOKE("library_downloaded_podcasts");
},
async libraryAlbums() : Promise<YtItem[]> {
    return await TAURI_INVOKE("library_albums");
},
async libraryArtists() : Promise<YtItem[]> {
    return await TAURI_INVOKE("library_artists");
},
async ytmHome() : Promise<HomePage> {
    return await TAURI_INVOKE("ytm_home");
},
async ytmHomeContinuation(continuation: Token) : Promise<HomePage> {
    return await TAURI_INVOKE("ytm_home_continuation", { continuation });
},
async ytmSearch(query: Text, requestId: string | null) : Promise<SearchPage> {
    return await TAURI_INVOKE("ytm_search", { query, requestId });
},
async ytmSearchContinuation(continuation: Token, requestId: string | null) : Promise<SearchPage> {
    return await TAURI_INVOKE("ytm_search_continuation", { continuation, requestId });
},
async syncYoutubeLibrary(mode: Keyword, requestId: string | null) : Promise<YouTubeSyncResult> {
    return await TAURI_INVOKE("sync_youtube_library", { mode, requestId });
},
async ytmAddToPlaylist(playlistId: YtId, videoId: VideoId) : Promise<null> {
    return await TAURI_INVOKE("ytm_add_to_playlist", { playlistId, videoId });
},
async ytmRemoveFromPlaylist(playlistId: YtId, videoId: VideoId, setVideoId: YtId) : Promise<null> {
    return await TAURI_INVOKE("ytm_remove_from_playlist", { playlistId, videoId, setVideoId });
},
async ytmCreatePlaylist(title: Name) : Promise<YtItem> {
    return await TAURI_INVOKE("ytm_create_playlist", { title });
},
async ytmPlaylist(playlistId: YtId, requestId: string | null) : Promise<PlaylistPage> {
    return await TAURI_INVOKE("ytm_playlist", { playlistId, requestId });
},
async ytmPlaylistContinuation(continuation: Token) : Promise<PlaylistContinuationPage> {
    return await TAURI_INVOKE("ytm_playlist_continuation", { continuation });
},
async ytmBrowse(browseId: YtId, params: string | null, requestId: string | null) : Promise<DetailPage> {
    return await TAURI_INVOKE("ytm_browse", { browseId, params, requestId });
},
async ytmBrowseContinuation(browseId: YtId, continuation: Token) : Promise<DetailPage> {
    return await TAURI_INVOKE("ytm_browse_continuation", { browseId, continuation });
},
async ytmDetail(kind: Keyword, browseId: YtId, requestId: string | null) : Promise<DetailPage> {
    return await TAURI_INVOKE("ytm_detail", { kind, browseId, requestId });
},
async ytmDetailContinuation(kind: Keyword, continuation: Token) : Promise<DetailPage> {
    return await TAURI_INVOKE("ytm_detail_continuation", { kind, continuation });
},
async ytmPodcastCacheDetailPage(browseId: YtId, page: DetailPage) : Promise<null> {
    return await TAURI_INVOKE("ytm_podcast_cache_detail_page", { browseId, page });
},
async ytmNext(videoId: VideoId, playlistId: string | null, setVideoId: string | null, index: number | null, params: string | null, continuation: string | null) : Promise<QueuePage> {
    return await TAURI_INVOKE("ytm_next", { videoId, playlistId, setVideoId, index, params, continuation });
},
async ytmRelated(browseId: YtId) : Promise<YtItem[]> {
    return await TAURI_INVOKE("ytm_related", { browseId });
},
async ytmQueueContinuation(continuation: Token) : Promise<QueuePage> {
    return await TAURI_INVOKE("ytm_queue_continuation", { continuation });
},
async ytmPlayer(videoId: VideoId, playlistId: string | null, audioQuality: string | null) : Promise<PlayerPayload> {
    return await TAURI_INVOKE("ytm_player", { videoId, playlistId, audioQuality });
},
/**
 * Called by the player when the audio element could not use the resolved stream (PLAY-030). A local
 * player-cache file is dropped so the next resolve fetches fresh; a remote stream marks its client as
 * failed for five minutes so the next resolve uses another client.
 */
async ytmReportStreamFailure(videoId: VideoId, streamUrl: LongText) : Promise<null> {
    return await TAURI_INVOKE("ytm_report_stream_failure", { videoId, streamUrl });
},
/**
 * Copyable, redacted report of the last resolution for a song (PLAY-006).
 */
async ytmPlaybackReport(videoId: VideoId) : Promise<string> {
    return await TAURI_INVOKE("ytm_playback_report", { videoId });
},
async historyAdd(item: YtItem) : Promise<number> {
    return await TAURI_INVOKE("history_add", { item });
},
async historyRecordPlaytime(historyId: number, playTimeMs: number) : Promise<null> {
    return await TAURI_INVOKE("history_record_playtime", { historyId, playTimeMs });
},
async historyItems() : Promise<YtItem[]> {
    return await TAURI_INVOKE("history_items");
},
async historyClear() : Promise<null> {
    return await TAURI_INVOKE("history_clear");
},
async libraryTopSongs(period: Keyword, limit: number) : Promise<YtItem[]> {
    return await TAURI_INVOKE("library_top_songs", { period, limit });
},
async libraryStats(period: Keyword) : Promise<StatsPayload> {
    return await TAURI_INVOKE("library_stats", { period });
},
async searchHistoryAdd(query: Text) : Promise<null> {
    return await TAURI_INVOKE("search_history_add", { query });
},
async searchHistoryItems() : Promise<string[]> {
    return await TAURI_INVOKE("search_history_items");
},
async searchHistoryClear() : Promise<null> {
    return await TAURI_INVOKE("search_history_clear");
},
async ytmToggleLike(videoId: VideoId, liked: boolean, item: YtItem | null) : Promise<null> {
    return await TAURI_INVOKE("ytm_toggle_like", { videoId, liked, item });
},
async fetchLyrics(title: Text, artist: Text, duration: number, album: string | null, id: string | null, requestId: string | null) : Promise<LyricsPayload> {
    return await TAURI_INVOKE("fetch_lyrics", { title, artist, duration, album, id, requestId });
},
async fetchLyricsFresh(title: Text, artist: Text, duration: number, album: string | null, id: string | null, requestId: string | null) : Promise<LyricsPayload> {
    return await TAURI_INVOKE("fetch_lyrics_fresh", { title, artist, duration, album, id, requestId });
},
async fetchLyricsFromProvider(title: Text, artist: Text, duration: number, album: string | null, id: string | null, provider: Keyword, requestId: string | null) : Promise<LyricsPayload> {
    return await TAURI_INVOKE("fetch_lyrics_from_provider", { title, artist, duration, album, id, provider, requestId });
},
async libraryToggleLiked(item: YtItem, liked: boolean) : Promise<null> {
    return await TAURI_INVOKE("library_toggle_liked", { item, liked });
},
async libraryEditItem(itemId: LibraryId, title: Name, artist: Text) : Promise<null> {
    return await TAURI_INVOKE("library_edit_item", { itemId, title, artist });
},
async libraryRefetchItem(id: LibraryId) : Promise<YtItem | null> {
    return await TAURI_INVOKE("library_refetch_item", { id });
},
async ytmToggleLibrary(videoId: VideoId, addToLibrary: boolean) : Promise<null> {
    return await TAURI_INVOKE("ytm_toggle_library", { videoId, addToLibrary });
},
async settingsGet() : Promise<SettingEntry[]> {
    return await TAURI_INVOKE("settings_get");
},
async settingsSet(key: Keyword, value: LongText) : Promise<null> {
    return await TAURI_INVOKE("settings_set", { key, value });
},
async backupCreate() : Promise<string> {
    return await TAURI_INVOKE("backup_create");
},
async backupRestore() : Promise<string> {
    return await TAURI_INVOKE("backup_restore");
},
async librarySaveItem(item: YtItem) : Promise<null> {
    return await TAURI_INVOKE("library_save_item", { item });
},
async libraryRemoveItem(id: LibraryId) : Promise<null> {
    return await TAURI_INVOKE("library_remove_item", { id });
},
async librarySongs() : Promise<YtItem[]> {
    return await TAURI_INVOKE("library_songs");
},
async libraryMixSongs() : Promise<YtItem[]> {
    return await TAURI_INVOKE("library_mix_songs");
},
async libraryLikedSongs() : Promise<YtItem[]> {
    return await TAURI_INVOKE("library_liked_songs");
},
async libraryUploadedSongs() : Promise<YtItem[]> {
    return await TAURI_INVOKE("library_uploaded_songs");
},
async libraryPlaylists() : Promise<LibraryPlaylistItem[]> {
    return await TAURI_INVOKE("library_playlists");
},
async libraryCreatePlaylist(title: Name) : Promise<YtItem> {
    return await TAURI_INVOKE("library_create_playlist", { title });
},
async libraryAddToPlaylist(playlistId: LibraryId, item: YtItem) : Promise<boolean> {
    return await TAURI_INVOKE("library_add_to_playlist", { playlistId, item });
},
async libraryRemoveFromPlaylist(playlistId: LibraryId, songId: LibraryId) : Promise<null> {
    return await TAURI_INVOKE("library_remove_from_playlist", { playlistId, songId });
},
async libraryPlaylistSongs(playlistId: LibraryId) : Promise<YtItem[]> {
    return await TAURI_INVOKE("library_playlist_songs", { playlistId });
},
async libraryItemState(id: LibraryId) : Promise<LibraryItemState> {
    return await TAURI_INVOKE("library_item_state", { id });
},
async libraryArtistState(artistId: LibraryId) : Promise<boolean> {
    return await TAURI_INVOKE("library_artist_state", { artistId });
},
async libraryToggleArtistBookmarked(artistId: LibraryId, name: Text, thumbnail: string | null, channelId: string | null, bookmarked: boolean) : Promise<null> {
    return await TAURI_INVOKE("library_toggle_artist_bookmarked", { artistId, name, thumbnail, channelId, bookmarked });
},
async speedDialToggle(item: YtItem, pinned: boolean) : Promise<null> {
    return await TAURI_INVOKE("speed_dial_toggle", { item, pinned });
},
async speedDialItems() : Promise<YtItem[]> {
    return await TAURI_INVOKE("speed_dial_items");
},
async openGoogleLogin() : Promise<null> {
    return await TAURI_INVOKE("open_google_login");
},
async accountRefreshProfile() : Promise<SessionStatus> {
    return await TAURI_INVOKE("account_refresh_profile");
},
async accountLogout() : Promise<null> {
    return await TAURI_INVOKE("account_logout");
},
async clearLocalLibraryKeepDownloads() : Promise<null> {
    return await TAURI_INVOKE("clear_local_library_keep_downloads");
},
async sessionStatus() : Promise<SessionStatus> {
    return await TAURI_INVOKE("session_status");
},
async openSpotifyLogin() : Promise<null> {
    return await TAURI_INVOKE("open_spotify_login");
},
async spotifySessionStatus() : Promise<SpotifySessionStatus> {
    return await TAURI_INVOKE("spotify_session_status");
},
async spotifyLogout() : Promise<null> {
    return await TAURI_INVOKE("spotify_logout");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Artist = { name: string; id: string | null }
export type DetailPage = { kind: string; title: string; subtitle: string; thumbnail: string | null; items: YtItem[]; continuation: string | null; browseId: string | null }
export type DownloadInfo = { songId: string; path: string; bytes: number; totalBytes: number | null; state: string; error: string | null; lyricsCached: boolean; artworkPath: string | null }
/**
 * Stable, machine-readable error codes. The TypeScript side mirrors these in
 * `src/lib/ipcError.ts`; renaming one is a contract change.
 */
export type ErrorCode = "invalid_argument" | "unauthenticated" | "not_found" | "conflict" | "cancelled" | "timeout" | "rate_limited" | "network" | "upstream" | "database" | "io" | "internal"
export type HomePage = { sections: HomeSection[]; continuation: string | null }
export type HomeSection = { title: string; label: string | null; thumbnail: string | null; browseId: string | null; params: string | null; browseKind: string | null; items: YtItem[] }
export type IpcError = { code: ErrorCode; message: string; retryable: boolean; 
/**
 * Extra diagnostic text. `None` by default; only set by explicit constructors with text
 * that is already safe to show.
 */
detail?: string | null }
/**
 * A short keyword: kinds, modes, periods, providers, audio qualities, setting keys.
 */
export type Keyword = string
/**
 * Ids of rows in the local Meld library (songs, playlists, artists, downloads).
 */
export type LibraryId = string
export type LibraryItemState = { liked: boolean; youtubeLiked: boolean; inLibrary: boolean; uploaded: boolean; pinned: boolean; podcastSaved: boolean }
export type LibraryPlaylistItem = ({ id: string; kind: string; title: string; subtitle: string; thumbnail: string | null; artists: Artist[]; browseId: string | null; playlistId: string | null; videoId: string | null; setVideoId: string | null; playPlaylistId: string | null; playVideoId: string | null; params: string | null; explicit?: boolean; musicVideoType: string | null; historyRemoveToken: string | null; albumId: string | null; albumTitle: string | null }) & { songCount: number; savedAt: number }
export type LocalItem = { id: string; kind: string; title: string; subtitle: string; thumbnail: string | null; artists: Artist[]; browseId: string | null; playlistId: string | null; videoId: string | null; setVideoId: string | null; playPlaylistId: string | null; playVideoId: string | null; params: string | null; explicit: boolean; musicVideoType: string | null; historyRemoveToken: string | null; albumId: string | null; albumTitle: string | null; localPath: string; duration: number }
/**
 * Longer values: setting values, thumbnails, stream URLs (never logged).
 */
export type LongText = string
export type LyricLine = { timeMs: number; text: string }
export type LyricsPayload = { provider: string; text: string; synced: boolean; matchedTitle: string; matchedArtist: string; lines: LyricLine[] }
/**
 * A required name (playlist title, new name, song title): non-empty, no control characters.
 */
export type Name = string
export type PlayerCacheUsage = { bytes: number; songs: number; limitMb: number }
export type PlayerPayload = { videoId: string; title: string | null; artist: string | null; streamUrl: string; mimeType: string; bitrate: number; expiresInSeconds: number; duration: number; 
/**
 * Resolver client that produced the stream (diagnostics only; never contains secrets).
 */
sourceClient: string | null }
export type PlaylistContinuationPage = { songs: YtItem[]; continuation: string | null }
export type PlaylistPage = { playlist: YtItem; songs: YtItem[]; continuation: string | null }
export type QueuePage = { title: string | null; items: YtItem[]; currentIndex: number | null; continuation: string | null; relatedBrowseId: string | null; relatedParams: string | null }
export type RemoteHistoryPage = { sections: RemoteHistorySection[] }
export type RemoteHistorySection = { title: string; songs: YtItem[] }
export type SearchPage = { items: YtItem[]; continuation: string | null }
export type SessionStatus = { authenticated: boolean; accountName: string | null; accountEmail: string | null; accountChannelHandle: string | null; accountAvatar: string | null }
export type SettingEntry = { key: string; value: string }
export type SpotifyFolderItem = { uri: string; name: string; totalChildren: number }
/**
 * A Spotify playlist id, track uid or other base62/hex identifier.
 */
export type SpotifyId = string
export type SpotifyLibraryNode = { folders: SpotifyFolderItem[]; playlists: SpotifyPlaylistItem[]; totalCount: number }
export type SpotifyLikedTracks = { tracks: SpotifyTrackItem[]; totalCount: number }
export type SpotifyPlaylistItem = { id: string; name: string; description: string | null; image: string | null; owner: string | null }
export type SpotifyProfile = { id: string; displayName: string | null; avatar: string | null }
export type SpotifySessionStatus = { authenticated: boolean; tokenExpiry: number | null }
export type SpotifyTrackItem = { id: string; uri: string; uid: string | null; name: string; artist: string; album: string; image: string | null; durationMs: number }
export type SpotifyTrackMatch = { id: string; uri: string; name: string; artist: string; durationMs: number }
export type SpotifyTrackPage = { tracks: SpotifyTrackItem[]; totalCount: number; offset: number; limit: number }
/**
 * A `spotify:` URI (track, folder, playlist).
 */
export type SpotifyUri = string
export type StatsGroup = { id: string; title: string; subtitle: string; thumbnail: string | null; plays: number }
export type StatsPayload = { period: string; totalPlays: number; totalMinutes: number; uniqueSongs: number; rows: StatsRow[]; artists: StatsGroup[]; albums: StatsGroup[] }
export type StatsRow = { item: YtItem; plays: number; minutes: number }
/**
 * Optional free text (artist, album, search query): may be empty, no control characters.
 */
export type Text = string
/**
 * InnerTube continuation tokens, feedback tokens and `params`.
 */
export type Token = string
export type UpdateSummary = { version: string; currentVersion: string; notes: string | null; date: string | null; 
/**
 * The portable ZIP cannot be updated in place yet; the UI offers the release page instead.
 */
portable: boolean }
/**
 * A YouTube video id: exactly 11 characters of `[A-Za-z0-9_-]`.
 */
export type VideoId = string
export type YouTubeSyncResult = { likedSongs: number; librarySongs: number; uploadedSongs: number; playlists: number }
/**
 * Browse, playlist, channel, podcast, entity and setVideoId values for YouTube Music.
 */
export type YtId = string
export type YtItem = { id: string; kind: string; title: string; subtitle: string; thumbnail: string | null; artists: Artist[]; browseId: string | null; playlistId: string | null; videoId: string | null; setVideoId: string | null; playPlaylistId: string | null; playVideoId: string | null; params: string | null; explicit?: boolean; musicVideoType: string | null; historyRemoveToken: string | null; albumId: string | null; albumTitle: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}

/** Every command by its invoked name, with named arguments (as `invoke` sends them). */
export type CommandMap = {
  account_logout: { args: {  }; result: null };
  account_refresh_profile: { args: {  }; result: SessionStatus };
  app_open_releases_page: { args: {  }; result: null };
  app_update_check: { args: {  }; result: UpdateSummary | null };
  app_update_install: { args: {  }; result: null };
  backup_create: { args: {  }; result: string };
  backup_restore: { args: {  }; result: string };
  clear_local_library_keep_downloads: { args: {  }; result: null };
  download_cancel: { args: { songId: LibraryId }; result: null };
  download_info: { args: { songId: LibraryId }; result: DownloadInfo | null };
  download_remove: { args: { songId: LibraryId }; result: null };
  download_start: { args: { item: YtItem; audioQuality?: string | null }; result: null };
  fetch_lyrics: { args: { title: Text; artist: Text; duration: number; album?: string | null; id?: string | null; requestId?: string | null }; result: LyricsPayload };
  fetch_lyrics_fresh: { args: { title: Text; artist: Text; duration: number; album?: string | null; id?: string | null; requestId?: string | null }; result: LyricsPayload };
  fetch_lyrics_from_provider: { args: { title: Text; artist: Text; duration: number; album?: string | null; id?: string | null; provider: Keyword; requestId?: string | null }; result: LyricsPayload };
  history_add: { args: { item: YtItem }; result: number };
  history_clear: { args: {  }; result: null };
  history_items: { args: {  }; result: YtItem[] };
  history_record_playtime: { args: { historyId: number; playTimeMs: number }; result: null };
  library_add_to_playlist: { args: { playlistId: LibraryId; item: YtItem }; result: boolean };
  library_albums: { args: {  }; result: YtItem[] };
  library_artist_state: { args: { artistId: LibraryId }; result: boolean };
  library_artists: { args: {  }; result: YtItem[] };
  library_create_playlist: { args: { title: Name }; result: YtItem };
  library_downloaded_podcasts: { args: {  }; result: LocalItem[] };
  library_downloads: { args: {  }; result: LocalItem[] };
  library_edit_item: { args: { itemId: LibraryId; title: Name; artist: Text }; result: null };
  library_item_state: { args: { id: LibraryId }; result: LibraryItemState };
  library_liked_songs: { args: {  }; result: YtItem[] };
  library_local_files: { args: {  }; result: LocalItem[] };
  library_mix_songs: { args: {  }; result: YtItem[] };
  library_player_cache: { args: {  }; result: YtItem[] };
  library_playlist_songs: { args: { playlistId: LibraryId }; result: YtItem[] };
  library_playlists: { args: {  }; result: LibraryPlaylistItem[] };
  library_refetch_item: { args: { id: LibraryId }; result: YtItem | null };
  library_remove_from_playlist: { args: { playlistId: LibraryId; songId: LibraryId }; result: null };
  library_remove_item: { args: { id: LibraryId }; result: null };
  library_save_item: { args: { item: YtItem }; result: null };
  library_saved_podcasts: { args: {  }; result: YtItem[] };
  library_songs: { args: {  }; result: YtItem[] };
  library_stats: { args: { period: Keyword }; result: StatsPayload };
  library_toggle_artist_bookmarked: { args: { artistId: LibraryId; name: Text; thumbnail?: string | null; channelId?: string | null; bookmarked: boolean }; result: null };
  library_toggle_liked: { args: { item: YtItem; liked: boolean }; result: null };
  library_top_songs: { args: { period: Keyword; limit: number }; result: YtItem[] };
  library_uploaded_songs: { args: {  }; result: YtItem[] };
  local_files_pick: { args: {  }; result: LocalItem[] };
  open_google_login: { args: {  }; result: null };
  open_spotify_login: { args: {  }; result: null };
  player_cache_clear: { args: {  }; result: number };
  player_cache_remove: { args: { songId: LibraryId }; result: null };
  player_cache_usage: { args: {  }; result: PlayerCacheUsage };
  request_cancel: { args: { requestId: Token }; result: boolean };
  search_history_add: { args: { query: Text }; result: null };
  search_history_clear: { args: {  }; result: null };
  search_history_items: { args: {  }; result: string[] };
  session_status: { args: {  }; result: SessionStatus };
  settings_get: { args: {  }; result: SettingEntry[] };
  settings_set: { args: { key: Keyword; value: LongText }; result: null };
  speed_dial_items: { args: {  }; result: YtItem[] };
  speed_dial_toggle: { args: { item: YtItem; pinned: boolean }; result: null };
  spotify_add_to_playlist: { args: { playlistId: SpotifyId; trackUri: SpotifyUri }; result: null };
  spotify_library_node: { args: { folderUri?: string | null }; result: SpotifyLibraryNode };
  spotify_liked_tracks: { args: {  }; result: SpotifyLikedTracks };
  spotify_logout: { args: {  }; result: null };
  spotify_match_for_youtube: { args: { youtubeId: VideoId }; result: SpotifyTrackMatch | null };
  spotify_move_in_playlist: { args: { playlistId: SpotifyId; uids: SpotifyId[]; beforeUid?: string | null }; result: null };
  spotify_override_youtube: { args: { spotifyId: LibraryId; youtubeId: VideoId; title: Text; artist: Text }; result: null };
  spotify_playlist_tracks: { args: { playlistId: SpotifyId; offset?: number | null }; result: SpotifyTrackPage };
  spotify_playlists: { args: {  }; result: SpotifyPlaylistItem[] };
  spotify_profile: { args: {  }; result: SpotifyProfile };
  spotify_remove_from_playlist: { args: { playlistId: SpotifyId; uid: SpotifyId }; result: null };
  spotify_rename_playlist: { args: { playlistId: SpotifyId; newName: Name }; result: null };
  spotify_resolve_youtube: { args: { youtubeId?: string | null; title: Text; artist: Text; durationSec: number }; result: SpotifyTrackMatch | null };
  spotify_session_status: { args: {  }; result: SpotifySessionStatus };
  sync_youtube_library: { args: { mode: Keyword; requestId?: string | null }; result: YouTubeSyncResult };
  ytm_add_to_playlist: { args: { playlistId: YtId; videoId: VideoId }; result: null };
  ytm_browse: { args: { browseId: YtId; params?: string | null; requestId?: string | null }; result: DetailPage };
  ytm_browse_continuation: { args: { browseId: YtId; continuation: Token }; result: DetailPage };
  ytm_create_playlist: { args: { title: Name }; result: YtItem };
  ytm_delete_uploaded_song: { args: { entityId: Token }; result: boolean };
  ytm_detail: { args: { kind: Keyword; browseId: YtId; requestId?: string | null }; result: DetailPage };
  ytm_detail_continuation: { args: { kind: Keyword; continuation: Token }; result: DetailPage };
  ytm_history: { args: {  }; result: RemoteHistoryPage };
  ytm_home: { args: {  }; result: HomePage };
  ytm_home_continuation: { args: { continuation: Token }; result: HomePage };
  ytm_next: { args: { videoId: VideoId; playlistId?: string | null; setVideoId?: string | null; index?: number | null; params?: string | null; continuation?: string | null }; result: QueuePage };
  ytm_playback_report: { args: { videoId: VideoId }; result: string };
  ytm_player: { args: { videoId: VideoId; playlistId?: string | null; audioQuality?: string | null }; result: PlayerPayload };
  ytm_playlist: { args: { playlistId: YtId; requestId?: string | null }; result: PlaylistPage };
  ytm_playlist_continuation: { args: { continuation: Token }; result: PlaylistContinuationPage };
  ytm_podcast_cache_detail_page: { args: { browseId: YtId; page: DetailPage }; result: null };
  ytm_podcast_channels: { args: {  }; result: YtItem[] };
  ytm_queue_continuation: { args: { continuation: Token }; result: QueuePage };
  ytm_refetch: { args: { videoId: VideoId }; result: YtItem | null };
  ytm_refresh_saved_podcasts: { args: {  }; result: number };
  ytm_related: { args: { browseId: YtId }; result: YtItem[] };
  ytm_remove_from_history: { args: { token: Token }; result: null };
  ytm_remove_from_playlist: { args: { playlistId: YtId; videoId: VideoId; setVideoId: YtId }; result: null };
  ytm_report_stream_failure: { args: { videoId: VideoId; streamUrl: LongText }; result: null };
  ytm_search: { args: { query: Text; requestId?: string | null }; result: SearchPage };
  ytm_search_continuation: { args: { continuation: Token; requestId?: string | null }; result: SearchPage };
  ytm_toggle_episode_saved: { args: { videoId: VideoId; saved: boolean; setVideoId?: string | null; item?: YtItem | null }; result: null };
  ytm_toggle_library: { args: { videoId: VideoId; addToLibrary: boolean }; result: null };
  ytm_toggle_like: { args: { videoId: VideoId; liked: boolean; item?: YtItem | null }; result: null };
  ytm_toggle_podcast_saved: { args: { podcastId: YtId; saved: boolean; title: Text; author?: string | null; thumbnail?: string | null }; result: null };
};
